server:
  port:8101
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.ultrapower.hsj.seller.dao.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl